### ISSUE TITLE
`Could not determine content start`

### ISSUE THREAD

**Issue by pprw** [marier-nico/adobe-connect-stitcher#1] opened 2021-09-24 15:16 UTC
When using this script, I have the following error
`Could not determine content start for file '/home/user/scripts/adobe-connect-stitcher/1/cameraVoip_1_4.xml'`

**Comment by marier-nico** [comment] 2021-09-24 15:24
Hmm, would it be possible to share the content of the xml file? Without it, there's not much I can do to find the problem :slightly_smiling_face:

**Comment by pprw** [comment] 2021-09-24 17:06
Sure. Here is the cameraVoip_1_4.xml' file.

https://textbin.net/myi2imyrzf

**Comment by marier-nico** [comment] 2021-09-26 00:19
Thanks for the file, I was able to reproduce the issue! It looks like Adobe Connect sometimes outputs dates in different locales, and I thought it would always output in an english locale.

Could you try the code from this branch? https://github.com/marier-nico/adobe-connect-stitcher/tree/feature/better-date-parsing

Note that you'll have to also `pip install dateparser` for it to work :tada:

**Comment by pprw** [comment] 2021-09-26 19:17
Thanks.
I cloned `feature/better-date-parsing` branch and installed `dateparser`.

Date error is gone but I have `Uncaught exception: list index out of range` instead.

**Comment by marier-nico** [comment] 2021-09-28 20:40
The error happened because there was no screenshare in the meeting, but the script expects at least one. I'll close this since the original problem was resolved :smile:

**Closed as completed by marier-nico** 2021-09-28 20:40 UTC
